/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 brand.gltf --tranform 
Author: Bowen154 (https://sketchfab.com/Bowen154)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/package-low-fb44add4533149ab9dc559ec34d1b96c
Title: Package Low
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brand.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.package_01_package_01_0.geometry} material={materials.package_01} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        {/* <mesh geometry={nodes.package_02_package_02_0.geometry} material={materials.package_02} position={[-150, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.package_03_package_03_0.geometry} material={materials.package_03} position={[150, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/brand.gltf')
