/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Plv.gltf --tranform 
Author: Franky Monyatsi (https://sketchfab.com/frankysydney)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vision-2036-exhibition-booth-bc60786f16b447e9827e83339e6ead1d
Title: Vision 2036 Exhibition Booth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/Plv.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Material3_1.geometry} material={materials.edge_color212191163255} />
        <lineSegments geometry={nodes.Material3_3.geometry} material={materials.edge_color0174237255} />
        <lineSegments geometry={nodes.Material3_4.geometry} material={materials.edge_color179179179255} />
        <lineSegments geometry={nodes.Material3_5.geometry} material={materials.edge_color18168157255} />
        <lineSegments geometry={nodes.Material3_6.geometry} material={materials.edge_color1879100255} />
        <lineSegments geometry={nodes.Material3_9.geometry} material={materials.edge_color242424255} />
        <lineSegments geometry={nodes.Material3_10.geometry} material={materials.edge_color254254254255} />
        <lineSegments geometry={nodes.Material3_11.geometry} material={materials.edge_color109120133255} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color194194194255} />
        <lineSegments geometry={nodes.Material3_17.geometry} material={materials.edge_color193193193255} />
        <lineSegments geometry={nodes.Material3_22.geometry} material={materials.edge_color198198198255} />
        <lineSegments geometry={nodes.Material2_24.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material2_25.geometry} material={materials.edge_color175175175255} />
        <lineSegments geometry={nodes.Material2_26.geometry} material={materials.edge_color12510490255} />
        <mesh geometry={nodes.Material2.geometry} material={materials['Vision_2036_Agency_logo-02']} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.material} />
        <mesh geometry={nodes.Material3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials['Pail_Wood_Texture_2-03']} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.acad6af96d29} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials['Visioon_2036_Panel-01']} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials['Vision_2036_Pillars-07']} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials['a75bc4b6-8a14-4db0-b95e-d0f51d14befa']} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.acade37f282d} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Aluminum} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials['Vision_2036_Pillars-06']} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials['Vision_2036_Pillars-05']} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Material3_7.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material3_8.geometry} material={materials['0135_DarkGray']} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.Granite_Brown} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.BANANA_BIG_PLANT1} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.BANANA_BIG_PLANT_BACK1} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.BANANA_BIG_PLANT_STVOL1} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.Helen_Phone} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.Helen_Skirt} />
        <mesh geometry={nodes.Material3_12.geometry} material={materials['01_-_Default']} />
        <mesh geometry={nodes.Material3_13.geometry} material={materials.arch20_document_01} />
        <mesh geometry={nodes.Material3_14.geometry} material={materials.arch20_document_02} />
        <mesh geometry={nodes.Material3_15.geometry} material={materials.Black} />
        <mesh geometry={nodes.Material3_16.geometry} material={materials.arch20_notes_page_01} />
        <mesh geometry={nodes.Material2_20.geometry} material={materials.Metal_Corrogated_Shiny} />
        <mesh geometry={nodes.Material2_21.geometry} material={materials['PDM_Grey_alu._MacBook_1']} />
        <mesh geometry={nodes.Material3_18.geometry} material={materials.PDM_MacBookAir_MacBook} />
        <mesh geometry={nodes.Material3_19.geometry} material={materials.PDM_Picture_02_MacBook} />
        <mesh geometry={nodes.Material3_20.geometry} material={materials.PDM_Camera_Green_MacBook_Air} />
        <mesh geometry={nodes.Material3_21.geometry} material={materials.PDM_Logo_MacBook} />
        <mesh geometry={nodes.Material2_22.geometry} material={materials['PDM_Grey_alu._MacBook']} />
        <mesh geometry={nodes.Material3_23.geometry} material={materials.PDM_Black_MacBook} />
        <mesh geometry={nodes.Material2_23.geometry} material={materials.PDM_Keyboard_MacBook} />
        <mesh geometry={nodes.Material3_24.geometry} material={materials.Wood_Veneer_01} />
        <mesh geometry={nodes.Material3_25.geometry} material={materials.Carrera_Marble} />
        <mesh geometry={nodes.Material3_26.geometry} material={materials['09_-_Default']} />
        <mesh geometry={nodes.Material3_27.geometry} material={materials['96363c9337b2d1aad24323b1d9efda72']} />
        <mesh geometry={nodes.Material3_28.geometry} material={materials['Visioon_2036_Panel-02']} />
        <mesh geometry={nodes.Material3_29.geometry} material={materials['Visioon_2036_Panel-03']} />
        <mesh geometry={nodes.Material3_30.geometry} material={materials['Visioon_2036_Panel-04']} />
        <mesh geometry={nodes.Material3_31.geometry} material={materials['Visioon_2036_Panel-05']} />
        <mesh geometry={nodes.Material3_32.geometry} material={materials['Visioon_2036_Panel-06']} />
        <mesh geometry={nodes.Material3_33.geometry} material={materials['Visioon_2036_Panel-07']} />
        <mesh geometry={nodes.Material3_34.geometry} material={materials['Visioon_2036_Panel-08']} />
        <mesh geometry={nodes.Material3_35.geometry} material={materials['Visioon_2036_Panel-09']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Plv.gltf')
